# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28de52499215a0bee4ee892833c5199be3d0c4194b2708cf27e025b0b71c0943ed9af44238f5bc66ba93ef24a8b0b6792a8d1a850ee2afaf4cfc84b67442fec

test:
  secret_key_base: 5e2e8baa765042e1c7d40c9a526023255355215c15a2abf76e5efe032e17f6414d9aeaeb5f2f0b4e3989189656a2434eee022678787aa347e75fc278654aa2d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
